import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import wavingHand from '../public/images/waving-hand.png';
import MapPin from '../components/mapPin';
import Projet from '../components/projetWrap';
import ContactForm from '../components/contactform';

const TitleWrap = styled.section`
	display: flex;
	flex-direction: column;
	align-items: center;
`;

const TitleBox = styled.div`
	padding: clamp(5em, 10vw, 10em) 0;
	color: ${(props) => props.theme.darkshades};

	h1,
	h2 {
		margin: 0;
		font-size: clamp(2.5em, 8vw, 5em);
		line-height: 1;
	}

	h1 {
		color: ${(props) => props.theme.main};
	}

	h2 {
		display: inline;
	}

	span,
	p,
	div {
		font-family: 'Merriweather', serif;
		font-weight: 700;
		margin: 0 0 0 4px;
	}

	p {
		margin-top: 0.75em;
		max-width: 360px;
		@media (min-width: 550px) {
			max-width: 450px;
		}
		@media (min-width: 768px) {
			max-width: 550px;
		}
		@media (min-width: 992px) {
			max-width: 720px;
		}
	}

	div {
		margin-top: 1em;
		display: flex;
		align-items: center;

		span {
			margin-right: 5px;
		}

		@media (min-width: 992px) {
			justify-content: flex-end;
		}
	}
`;

export default function Home() {
	return (
		<>
			<Head>
				<title>Simon Gravel</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<meta property='og:url' content='https://simongravel.ca/' />
				<meta property='og:type' content='website' />
				<meta property='og:title' content='Simon Gravel' />
				<meta name='twitter:card' content='summary' />
				<meta
					property='og:description'
					content='Simon Gravel est un développeur et désigneur Web qui se spécialise en tout ce qui touche au JavaScript.'
				/>
				<meta property='og:image' content={'/ogImage.jpg'} />
			</Head>

			<div className='container'>
				<TitleWrap>
					<TitleBox>
						<span>
							Salut!
							<Image src={wavingHand} alt='Signe de la main' /> Je m&apos;appelle
						</span>
						<h1>Simon Gravel.</h1>
						<h2>Développeur Web.</h2>
						<p>
							J&apos;aime construire des applications pour le Web et je me concentre particulièrement sur
							tout ce qui touche au JavaScript. Je suis aussi designeur à mes heures!
						</p>
						<div>
							<span>Québec, Canada</span> <MapPin />
						</div>
					</TitleBox>
				</TitleWrap>
				<Projet />
				<ContactForm />
			</div>
		</>
	);
}
